### ISSUE TITLE
The target should also have all the libraries 

### ISSUE THREAD

**Issue by therealbappi** [Ankit404butfound/RandomProject#2]
To execute the script, the target should have the libraries, this actually isn't that stealthy.

**Comment by Ankit404butfound** [comment]
> To execute the script, the target should have the libraries, this actually isn't that stealthy.

Although, the issue has been closed but I need to clear it that when .py is converted to executables, all the libraries are also converted along with it.

**Comment by therealbappi** [comment]
When you send the. Py to a mac user,exe will not be an option,so that was
my concern.
Anyways i found the solution thanks man.
Nice work.
